# Generated by Django 5.1.1 on 2024-10-02 12:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_eventparticipant_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='entry_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('Register', 'Register'), ('Attended', 'Attended'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='No Show', max_length=30),
        ),
    ]
