# Generated by Django 5.1.1 on 2024-10-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_eventparticipant_status_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('Register', 'Register'), ('Attended', 'Attended'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='No Show', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='entry_code',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
