# Generated by Django 5.1.1 on 2024-10-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0014_alter_event_status_alter_payment_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_successful',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Verification', 'Verification'), ('Successful', 'Successful'), ('Failed', 'Failed')], default='Verification', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Show', 'Show'), ('Close', 'Close'), ('Past', 'Past')], default='Show', max_length=10),
        ),
    ]
