# Generated by Django 5.1.1 on 2024-10-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0015_remove_payment_is_successful_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Show', 'Show'), ('Close', 'Close'), ('Past', 'Past')], default='Show', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Verification', 'Verification'), ('Successful', 'Successful'), ('Failed', 'Failed')], default='Verification', max_length=50),
        ),
    ]
