# Generated by Django 5.1.2 on 2024-10-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0021_alter_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('บริษัท', 'Company'), ('บุคคล', 'Individual')], default='บุคคล', max_length=10),
        ),
    ]
